"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type View = "dashboard" | "entries" | "types";
type Entry = { id:number; groupId:string; description:string; contact:string; category:string; type:"income"|"expense"; amountCents:number; dueDate:string; installment:number; installments:number; interestType:"none"|"simple"|"compound"; interestRateBps:number; paid:boolean };
type MovementType = { id:number; name:string };
const fallbackIncomeTypes = ["Vendas","Serviços","Outros"];
const fallbackExpenseTypes = ["Moradia","Fornecedores","Transporte","Alimentação","Saúde","Lazer","Outros"];
const money = new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const monthName = new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"});
const shortMonth = new Intl.DateTimeFormat("pt-BR",{month:"short"});
function isoMonth(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`}
function moveMonth(month:string,offset:number){const [y,m]=month.split("-").map(Number);return isoMonth(new Date(y,m-1+offset,1))}
function labelDate(value:string){return new Intl.DateTimeFormat("pt-BR").format(new Date(`${value}T12:00:00`))}

export function CashFlowApp({view}:{view:View}){
  const [entries,setEntries]=useState<Entry[]>([]); const [movementTypes,setMovementTypes]=useState<{income:MovementType[];expense:MovementType[]}>({income:[],expense:[]}); const [month,setMonth]=useState(isoMonth()); const [loading,setLoading]=useState(true); const [open,setOpen]=useState(false); const [error,setError]=useState(""); const [filter,setFilter]=useState<"all"|"income"|"expense"|"pending">("all"); const [search,setSearch]=useState(""); const [categoryFilter,setCategoryFilter]=useState("all"); const [mobileNav,setMobileNav]=useState(false); const [userName,setUserName]=useState("Usuário");
  useEffect(()=>{Promise.all([fetch("/api/entries"),fetch("/api/movement-types"),fetch("/api/auth/status")]).then(async([entryResponse,typeResponse,authResponse])=>{const entryData=await entryResponse.json();const typeData=await typeResponse.json();const authData=await authResponse.json();if(!entryResponse.ok||!typeResponse.ok||!authResponse.ok)throw new Error();setEntries(entryData.entries);setMovementTypes(typeData);const login=String(authData.user?.username||"Usuário");setUserName(login.charAt(0).toUpperCase()+login.slice(1))}).catch(()=>setError("Não foi possível carregar os dados agora.")).finally(()=>setLoading(false))},[]);
  const monthEntries=useMemo(()=>entries.filter(e=>e.dueDate.startsWith(month)),[entries,month]);
  const totals=useMemo(()=>monthEntries.reduce((a,e)=>{a[e.type]+=e.amountCents;if(!e.paid){a.pending++;if(e.type==="income")a.receivable+=e.amountCents;else a.payable+=e.amountCents}else a.paid+=e.amountCents;return a},{income:0,expense:0,pending:0,paid:0,receivable:0,payable:0}),[monthEntries]);
  const visible=useMemo(()=>{const term=search.trim().toLocaleLowerCase("pt-BR");return monthEntries.filter(e=>filter==="all"||(filter==="pending"?!e.paid:e.type===filter)).filter(e=>categoryFilter==="all"||e.category===categoryFilter).filter(e=>!term||`${e.description} ${e.contact} ${e.category}`.toLocaleLowerCase("pt-BR").includes(term)).sort((a,b)=>a.dueDate.localeCompare(b.dueDate))},[monthEntries,filter,search,categoryFilter]);
  const categoryTotals=useMemo(()=>{const map=new Map<string,number>();monthEntries.filter(e=>e.type==="expense").forEach(e=>map.set(e.category,(map.get(e.category)||0)+e.amountCents));return [...map].sort((a,b)=>b[1]-a[1])},[monthEntries]);
  const evolution=useMemo(()=>Array.from({length:6},(_,i)=>{const key=moveMonth(month,i-5);const rows=entries.filter(e=>e.dueDate.startsWith(key));return {key,label:shortMonth.format(new Date(`${key}-02T12:00:00`)).replace(".",""),income:rows.filter(e=>e.type==="income").reduce((s,e)=>s+e.amountCents,0),expense:rows.filter(e=>e.type==="expense").reduce((s,e)=>s+e.amountCents,0)}}),[entries,month]);
  const maxChart=Math.max(1,...evolution.flatMap(e=>[e.income,e.expense]));
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const form=new FormData(event.currentTarget);const response=await fetch("/api/entries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(form))});const data=await response.json();if(!response.ok)return setError(data.error||"Confira os dados e tente novamente.");setEntries(c=>[...c,...data.entries]);setMonth(String(form.get("dueDate")).slice(0,7));setOpen(false)}
  async function togglePaid(entry:Entry){const r=await fetch(`/api/entries/${entry.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({paid:!entry.paid})});if(r.ok)setEntries(c=>c.map(i=>i.id===entry.id?{...i,paid:!i.paid}:i))}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});window.location.href="/login"}
  const monthDate=new Date(`${month}-02T12:00:00`); const balance=totals.income-totals.expense;
  const titles={dashboard:["Visão geral","Acompanhe o presente e o futuro do seu caixa"],entries:["Lançamentos","Organize entradas, saídas e parcelas"],types:["Configurações","Organize os tipos de entradas e saídas"]};
  return <div className="appLayout">
    <aside className={`sidebar ${mobileNav?"show":""}`}>
      <Link className="brand" href="/dashboard"><span>c</span> clara fluxo</Link>
      <nav><p>MENU PRINCIPAL</p><Link className={view==="dashboard"?"active":""} href="/dashboard"><i>⌂</i> Dashboard</Link><Link className={view==="entries"?"active":""} href="/lancamentos"><i>⇄</i> Lançamentos</Link><p className="secondaryNavLabel">CONFIGURAÇÕES</p><Link className={view==="types"?"active":""} href="/tipos-de-movimentacao"><i>≡</i> Tipos de movimentação</Link></nav>
      <div className="sideHelp"><b>Precisa de ajuda?</b><span>Veja como organizar seu fluxo de caixa.</span><button>Ver guia rápido</button></div>
      <div className="profile"><div className="avatar">{userName.slice(0,2).toUpperCase()}</div><div><b>{userName}</b><span>Usuário</span></div><button className="logoutButton" onClick={logout} aria-label="Sair" title="Sair">Sair</button></div>
    </aside>
    <main className="mainArea">
      <header className="appTop"><button className="menuButton" onClick={()=>setMobileNav(!mobileNav)} aria-label="Abrir menu">☰</button><div><p className="eyebrow">{titles[view][0]}</p><h1>{titles[view][1]}</h1></div><div className="topActions"><button className="notification" aria-label="Notificações">●</button><button className="primary" onClick={()=>setOpen(true)}>＋ Novo lançamento</button></div></header>
      <section className="monthNav"><button onClick={()=>setMonth(moveMonth(month,-1))}>←</button><strong>{monthName.format(monthDate)}</strong><button onClick={()=>setMonth(moveMonth(month,1))}>→</button><button className="today" onClick={()=>setMonth(isoMonth())}>Hoje</button></section>
      {error&&<p className="notice">{error}</p>}
      {view==="dashboard"&&<Dashboard totals={totals} balance={balance} evolution={evolution} maxChart={maxChart} categories={categoryTotals} entries={monthEntries} allEntries={entries} month={month} loading={loading} onToggle={togglePaid}/>} 
      {view==="entries"&&<Entries entries={visible} categoryOptions={[...movementTypes.income,...movementTypes.expense].map(item=>item.name)} loading={loading} filter={filter} setFilter={setFilter} search={search} setSearch={setSearch} categoryFilter={categoryFilter} setCategoryFilter={setCategoryFilter} onToggle={togglePaid} onNew={()=>setOpen(true)}/>} 
      {view==="types"&&<MovementTypes types={movementTypes} setTypes={setMovementTypes}/>} 
    </main>
    {open&&<EntryModal types={movementTypes} onClose={()=>setOpen(false)} onSubmit={submit}/>} 
  </div>
}

function Dashboard({totals,balance,evolution,maxChart,categories,entries,allEntries,month,loading,onToggle}:{totals:{income:number;expense:number;pending:number;paid:number;receivable:number;payable:number};balance:number;evolution:{key:string;label:string;income:number;expense:number}[];maxChart:number;categories:[string,number][];entries:Entry[];allEntries:Entry[];month:string;loading:boolean;onToggle:(e:Entry)=>void}){
  const expensePct=totals.income?Math.round(totals.expense/totals.income*100):0;
  const future=allEntries.filter(e=>!e.paid&&e.dueDate>=`${moveMonth(month,1)}-01`).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
  const futureReceivable=future.filter(e=>e.type==="income").reduce((sum,e)=>sum+e.amountCents,0);
  const futurePayable=future.filter(e=>e.type==="expense").reduce((sum,e)=>sum+e.amountCents,0);
  return <div className="content"><section className="kpis"><article><div className="kpiTop"><span className="kpiIcon green">↗</span><em>ENTRADAS</em></div><strong>{money.format(totals.income/100)}</strong><small>Receitas com vencimento no mês</small></article><article><div className="kpiTop"><span className="kpiIcon coral">↘</span><em>SAÍDAS</em></div><strong>{money.format(totals.expense/100)}</strong><small>{expensePct}% das entradas do período</small></article><article className="featured"><div className="kpiTop"><span className="kpiIcon gold">◇</span><em>SALDO PROJETADO</em></div><strong>{money.format(balance/100)}</strong><small>Resultado previsto pelo vencimento</small></article><article className="openBalance receivable"><div className="kpiTop"><span className="kpiIcon green">＋</span><em>SALDO A RECEBER</em></div><strong>{money.format(totals.receivable/100)}</strong><small>Em aberto com vencimento no mês</small></article><article className="openBalance payable"><div className="kpiTop"><span className="kpiIcon coral">−</span><em>SALDO A PAGAR</em></div><strong>{money.format(totals.payable/100)}</strong><small>Em aberto com vencimento no mês</small></article><article><div className="kpiTop"><span className="kpiIcon blue">✓</span><em>REALIZADO</em></div><strong>{money.format(totals.paid/100)}</strong><small>Valores já confirmados no período</small></article></section>
  <section className="dashGrid"><article className="panel chartPanel"><PanelHead title="Evolução do caixa" subtitle="Entradas e saídas nos últimos 6 meses"/><div className="legend"><span><i className="dot incomeDot"/>Entradas</span><span><i className="dot expenseDot"/>Saídas</span></div><div className="barChart">{evolution.map(e=><div className="barGroup" key={e.key}><div className="bars"><span className="bar in" style={{height:`${Math.max(3,e.income/maxChart*100)}%`}} title={money.format(e.income/100)}/><span className="bar out" style={{height:`${Math.max(3,e.expense/maxChart*100)}%`}} title={money.format(e.expense/100)}/></div><b>{e.label}</b></div>)}</div></article>
  <article className="panel categoryPanel"><PanelHead title="Saídas por categoria" subtitle="Distribuição deste mês"/>{categories.length?<div className="categoryList">{categories.slice(0,5).map(([name,value],i)=><div key={name}><div className="categoryLine"><span><i className={`catColor c${i}`}/>{name}</span><b>{money.format(value/100)}</b></div><div className="progress"><span className={`c${i}`} style={{width:`${value/categories[0][1]*100}%`}}/></div></div>)}</div>:<Empty compact/>}</article></section>
  <section className="panel recent"><PanelHead title="Lançamentos do período" subtitle="Movimentações pela data de vencimento no mês selecionado" action={<Link href="/lancamentos">Ver todos →</Link>}/><LedgerTable entries={[...entries].sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,5)} loading={loading} onToggle={onToggle}/></section>
  <section className="futureSection"><div className="futureTitle"><div><p className="eyebrow">PRÓXIMOS MESES</p><h2>Movimentações futuras</h2><span>Calculadas automaticamente pela data de vencimento de cada lançamento.</span></div><Link href="/lancamentos">Gerenciar lançamentos →</Link></div><div className="futureBalances"><article className="futureReceive"><span>FUTURO A RECEBER</span><strong>{money.format(futureReceivable/100)}</strong><small>{future.filter(e=>e.type==="income").length} lançamento(s) em aberto</small></article><article className="futurePay"><span>FUTURO A PAGAR</span><strong>{money.format(futurePayable/100)}</strong><small>{future.filter(e=>e.type==="expense").length} lançamento(s) em aberto</small></article><article className="futureNet"><span>SALDO FUTURO</span><strong>{money.format((futureReceivable-futurePayable)/100)}</strong><small>Diferença entre o que entra e sai</small></article></div><section className="panel"><PanelHead title="Próximos vencimentos" subtitle="Primeiras movimentações após o período selecionado"/><LedgerTable entries={future.slice(0,6)} loading={loading} onToggle={onToggle}/></section></section></div>
}
function Entries({entries,categoryOptions,loading,filter,setFilter,search,setSearch,categoryFilter,setCategoryFilter,onToggle,onNew}:{entries:Entry[];categoryOptions:string[];loading:boolean;filter:string;setFilter:(v:"all"|"income"|"expense"|"pending")=>void;search:string;setSearch:(v:string)=>void;categoryFilter:string;setCategoryFilter:(v:string)=>void;onToggle:(e:Entry)=>void;onNew:()=>void}){const hasFilters=filter!=="all"||search!==""||categoryFilter!=="all";function clear(){setFilter("all");setSearch("");setCategoryFilter("all")}return <div className="content"><section className="panel entriesPanel"><div className="ledgerHead"><div><h2>Todos os lançamentos</h2><p>Gerencie os vencimentos e confirme pagamentos</p></div><div className="filters">{([["all","Todos"],["income","Entradas"],["expense","Saídas"],["pending","Pendentes"]] as const).map(([value,label])=><button className={filter===value?"active":""} key={value} onClick={()=>setFilter(value)}>{label}</button>)}</div></div><div className="filterBar"><label className="searchField"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar descrição ou contato" aria-label="Buscar lançamentos"/></label><label className="categorySelect"><span>Categoria</span><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="all">Todas</option>{[...new Set(categoryOptions)].map(c=><option key={c} value={c}>{c}</option>)}</select></label><div className="filterResult"><b>{entries.length}</b> {entries.length===1?"resultado":"resultados"}{hasFilters&&<button onClick={clear}>Limpar</button>}</div></div><LedgerTable entries={entries} loading={loading} onToggle={onToggle}/>{!loading&&entries.length===0&&!hasFilters&&<button className="emptyAction" onClick={onNew}>＋ Criar lançamento</button>}</section></div>}
function Accounts({kind,entries,loading,onToggle,onNew}:{kind:"income"|"expense";entries:Entry[];loading:boolean;onToggle:(e:Entry)=>void;onNew:()=>void}){const [status,setStatus]=useState<"open"|"overdue"|"settled"|"all">("open");const today=new Date().toISOString().slice(0,10);const rows=entries.filter(e=>e.type===kind);const overdue=rows.filter(e=>!e.paid&&e.dueDate<today);const open=rows.filter(e=>!e.paid&&e.dueDate>=today);const settled=rows.filter(e=>e.paid);const shown=(status==="overdue"?overdue:status==="settled"?settled:status==="open"?open:rows).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));const sum=(list:Entry[])=>list.reduce((s,e)=>s+e.amountCents,0);const noun=kind==="expense"?"pagamento":"recebimento";return <div className="content accountPage"><section className="accountKpis"><article><span>EM ABERTO</span><strong>{money.format(sum(open)/100)}</strong><small>{open.length} conta(s) a vencer</small></article><article className="danger"><span>VENCIDAS</span><strong>{money.format(sum(overdue)/100)}</strong><small>{overdue.length} conta(s) precisam de atenção</small></article><article><span>{kind==="expense"?"PAGO":"RECEBIDO"}</span><strong>{money.format(sum(settled)/100)}</strong><small>{settled.length} baixa(s) confirmadas</small></article></section><section className="panel entriesPanel"><div className="ledgerHead"><div><h2>{kind==="expense"?"Agenda de pagamentos":"Agenda de recebimentos"}</h2><p>Controle por vencimento, situação e {kind==="expense"?"fornecedor":"cliente"}</p></div><div className="filters">{([["open","Em aberto"],["overdue","Vencidas"],["settled",kind==="expense"?"Pagas":"Recebidas"],["all","Todas"]] as const).map(([value,label])=><button className={status===value?"active":""} key={value} onClick={()=>setStatus(value)}>{label}</button>)}</div></div><AccountTable entries={shown} loading={loading} kind={kind} onToggle={onToggle}/>{!loading&&shown.length===0&&<button className="emptyAction" onClick={onNew}>＋ Adicionar conta</button>}</section><p className="accountTip">Marque a caixa ao lado de cada item para confirmar o {noun}. Parcelas são controladas individualmente.</p></div>}
function AccountTable({entries,loading,kind,onToggle}:{entries:Entry[];loading:boolean;kind:"income"|"expense";onToggle:(e:Entry)=>void}){const today=new Date().toISOString().slice(0,10);return <div className="tableWrap"><table className="accountTable"><thead><tr><th>Status</th><th>Descrição</th><th>{kind==="expense"?"Fornecedor":"Cliente"}</th><th>Vencimento</th><th>Situação</th><th>Valor</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="empty">Carregando contas…</td></tr>:entries.length===0?<tr><td colSpan={6}><Empty/></td></tr>:entries.map(e=>{const overdue=!e.paid&&e.dueDate<today;return <tr key={e.id} className={overdue?"overdueRow":""}><td><button className={`status ${e.paid?"done":""}`} onClick={()=>onToggle(e)}>{e.paid?"✓":""}</button></td><td><b>{e.description}</b>{e.installments>1&&<small className="accountInstallment">Parcela {e.installment} de {e.installments}</small>}</td><td>{e.contact||<span className="mutedDash">Não informado</span>}</td><td>{labelDate(e.dueDate)}</td><td><span className={`situation ${e.paid?"settled":overdue?"overdue":"open"}`}>{e.paid?(kind==="expense"?"Pago":"Recebido"):overdue?"Vencido":"Em aberto"}</span></td><td className={kind}>{money.format(e.amountCents/100)}</td></tr>})}</tbody></table></div>}
function Reports({totals,balance,evolution,maxChart,categories}:{totals:{income:number;expense:number};balance:number;evolution:{key:string;label:string;income:number;expense:number}[];maxChart:number;categories:[string,number][]}){const margin=totals.income?Math.round(balance/totals.income*100):0;return <div className="content reports"><section className="reportSummary"><div><span>Resultado do mês</span><strong>{money.format(balance/100)}</strong><small className={balance>=0?"positive":"negative"}>{margin}% de margem sobre as entradas</small></div><div><span>Total movimentado</span><strong>{money.format((totals.income+totals.expense)/100)}</strong><small>Entradas + saídas</small></div><div><span>Maior categoria de saída</span><strong>{categories[0]?.[0]||"—"}</strong><small>{categories[0]?money.format(categories[0][1]/100):"Sem despesas no mês"}</small></div></section><section className="panel reportChart"><PanelHead title="Comparativo mensal" subtitle="Visão consolidada dos últimos 6 meses"/><div className="wideChart">{evolution.map(e=><div className="wideRow" key={e.key}><b>{e.label}</b><div><span className="wideIn" style={{width:`${e.income/maxChart*100}%`}}/><span className="wideOut" style={{width:`${e.expense/maxChart*100}%`}}/></div><small>{money.format((e.income-e.expense)/100)}</small></div>)}</div></section><section className="panel categoryReport"><PanelHead title="Detalhamento por categoria" subtitle="Participação das despesas no mês"/><div className="reportRows">{categories.map(([name,value])=><div key={name}><span>{name}</span><b>{money.format(value/100)}</b><em>{totals.expense?Math.round(value/totals.expense*100):0}%</em></div>)}{!categories.length&&<Empty compact/>}</div></section></div>}
function MovementTypes({types,setTypes}:{types:{income:MovementType[];expense:MovementType[]};setTypes:React.Dispatch<React.SetStateAction<{income:MovementType[];expense:MovementType[]}>>}){const [error,setError]=useState("");async function add(event:FormEvent<HTMLFormElement>,kind:"income"|"expense"){event.preventDefault();setError("");const form=new FormData(event.currentTarget);const response=await fetch("/api/movement-types",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,name:form.get("name")})});const data=await response.json();if(!response.ok)return setError(data.error);setTypes(current=>({...current,[kind]:[...current[kind],data.item].sort((a,b)=>a.name.localeCompare(b.name,"pt-BR"))}));event.currentTarget.reset()}async function remove(kind:"income"|"expense",id:number){const response=await fetch(`/api/movement-types/${kind}/${id}`,{method:"DELETE"});if(response.ok)setTypes(current=>({...current,[kind]:current[kind].filter(item=>item.id!==id)}))}return <div className="content typeModule"><div className="typeIntro"><div><h2>Tipos de movimentação</h2><p>Personalize as opções disponíveis ao cadastrar um lançamento.</p></div></div>{error&&<p className="notice typeNotice">{error}</p>}<section className="typeTables"><TypeTable title="Tipos de entrada" hint="Ex.: vendas, serviços e comissões" kind="income" items={types.income} onAdd={add} onRemove={remove}/><TypeTable title="Tipos de saída" hint="Ex.: fornecedores, aluguel e impostos" kind="expense" items={types.expense} onAdd={add} onRemove={remove}/></section></div>}
function TypeTable({title,hint,kind,items,onAdd,onRemove}:{title:string;hint:string;kind:"income"|"expense";items:MovementType[];onAdd:(e:FormEvent<HTMLFormElement>,kind:"income"|"expense")=>void;onRemove:(kind:"income"|"expense",id:number)=>void}){return <section className={`panel typeTable ${kind}`}><div className="typeTableHead"><span className="typeSymbol">{kind==="income"?"↗":"↘"}</span><div><h2>{title}</h2><p>{hint}</p></div></div><form className="addType" onSubmit={e=>onAdd(e,kind)}><input name="name" required maxLength={50} placeholder="Nome do novo tipo"/><button>＋ Adicionar</button></form><div className="typeRows">{items.length?items.map(item=><div key={item.id}><span>{item.name}</span><button onClick={()=>onRemove(kind,item.id)} aria-label={`Excluir ${item.name}`}>×</button></div>):<p>Nenhum tipo cadastrado.</p>}</div></section>}
function PanelHead({title,subtitle,action}:{title:string;subtitle:string;action?:React.ReactNode}){return <div className="panelHead"><div><h2>{title}</h2><p>{subtitle}</p></div>{action}</div>}
function Empty({compact=false}:{compact?:boolean}){return <div className={`empty ${compact?"compact":""}`}><b>Nenhum lançamento por aqui.</b><span>Adicione uma entrada ou saída para começar.</span></div>}
function LedgerTable({entries,loading,onToggle}:{entries:Entry[];loading:boolean;onToggle:(e:Entry)=>void}){return <div className="tableWrap"><table><thead><tr><th>Status</th><th>Descrição</th><th>Categoria</th><th>Vencimento</th><th>Parcela</th><th>Valor</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="empty">Carregando seu caixa…</td></tr>:entries.length===0?<tr><td colSpan={6}><Empty/></td></tr>:entries.map(e=><tr key={e.id}><td><button className={`status ${e.paid?"done":""}`} onClick={()=>onToggle(e)} aria-label={e.paid?"Marcar como pendente":"Marcar como pago"}>{e.paid?"✓":""}</button></td><td><b>{e.description}</b><small className="mobileCategory">{e.category}</small></td><td><span className="tag">{e.category}</span></td><td>{labelDate(e.dueDate)}</td><td>{e.installments>1?`${e.installment}/${e.installments}`:"—"}</td><td className={e.type}>{e.type==="expense"?"− ":"+ "}{money.format(e.amountCents/100)}</td></tr>)}</tbody></table></div>}
function EntryModal({types,onClose,onSubmit}:{types:{income:MovementType[];expense:MovementType[]};onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){const [entryKind,setEntryKind]=useState<"income"|"expense">("income");const custom=(entryKind==="income"?types.income:types.expense).map(item=>item.name);const options=custom.length?custom:(entryKind==="income"?fallbackIncomeTypes:fallbackExpenseTypes);return <div className="modalBackdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true"><button className="close" onClick={onClose}>×</button><p className="eyebrow">NOVO LANÇAMENTO</p><h2>O que aconteceu no seu caixa?</h2><p className="modalIntro">Se for parcelado, criamos todos os próximos vencimentos para você.</p><form onSubmit={onSubmit}><div className="typeChoice"><label><input type="radio" name="type" value="income" checked={entryKind==="income"} onChange={()=>setEntryKind("income")}/><span>↗ Entrada / A receber</span></label><label><input type="radio" name="type" value="expense" checked={entryKind==="expense"} onChange={()=>setEntryKind("expense")}/><span>↘ Saída / A pagar</span></label></div><label className="field"><span>Descrição</span><input name="description" required placeholder="Ex.: Notebook para o escritório"/></label><label className="field"><span>Cliente ou fornecedor</span><input name="contact" placeholder="Ex.: Empresa Silva Ltda."/></label><div className="formGrid"><label className="field"><span>Valor principal</span><input name="amount" required inputMode="decimal" placeholder="0,00"/></label><label className="field"><span>Tipo de {entryKind==="income"?"entrada":"saída"}</span><select name="category">{options.map(c=><option key={c}>{c}</option>)}</select></label></div><div className="formGrid"><label className="field"><span>Primeiro vencimento</span><input type="date" name="dueDate" required defaultValue={`${isoMonth()}-15`}/></label><label className="field"><span>Número de parcelas</span><input type="number" name="installments" min="1" max="60" defaultValue="1" required/></label></div><div className="interestBox"><p>Juros do parcelamento</p><div className="formGrid"><label className="field"><span>Tipo de juros</span><select name="interestType" defaultValue="none"><option value="none">Sem juros</option><option value="simple">Juros simples</option><option value="compound">Juros compostos</option></select></label><label className="field"><span>Taxa ao mês (%)</span><input name="interestRate" type="number" min="0" max="100" step="0.01" defaultValue="0" inputMode="decimal"/></label></div><small>Nos juros simples, a taxa incide sobre o principal. Nos compostos, incide sobre o saldo acumulado a cada mês.</small></div><p className="splitHint">O total com juros será dividido igualmente, preservando a soma exata dos centavos.</p><button className="primary submit">Salvar lançamento</button></form></section></div>}
